### ISSUE TITLE
No Event "MintingUpdate" for adjust if minted is decreased

### ISSUE THREAD

**Issue by samclassix** [Frankencoin-ZCHF/frankencoin-api#11]
# Issue with state

How to replicate:

- Open Position (minted: 0 ZCHF)
- Call "adjust" and mint some ZCHF e.g. minted: 1000 ZCHF
- "MintingUpdate" event triggered: ponder & api will index and update state
- Call "adjust" and return your outstanding mint to 0 ZCHF
- Tx done. Debt paid. No event triggered, like "MintingUpdate"
- Ponder is not aware of the minted: 0 ZCHF state and remains at the old state
- Api is not aware of the new minted: 0 ZCHF state, because:

1. Api depends on ponder indexed state and blockchain stored history to minimize fetching manual data.
2. It was anticipated that the event "MintingUpdate" gets triggered if you adjust your position incl. minting amount.
3. Event MintingUpdate includes **uint256 minted**, however, never called/triggered. never indexed.

Explanation:

- if there is no event, then there is no ponder indexing
- if there is no ponder indexing, there is no update in api
- Therefor also no updates for the application

![Screenshot 2024-08-06 at 3 31 57 PM](https://github.com/user-attachments/assets/c3812d57-5183-4c6e-a31f-ab4e34b73365)

# Similar issue is already known with collateral transfer

- solved by overriding the balance of the position to include ERC20 transfer events
![Screenshot 2024-08-06 at 4 00 35 PM](https://github.com/user-attachments/assets/95549bb3-bb0f-411b-b828-5fcc9d07e735)

# Solvable?

- fetching latest minted of each position?

**Comment by samclassix** [comment]
FIXME: 
- position: collateral balanceOf
- position: minted
- use multiCall and replace single eth_data requests

**Comment by samclassix** [comment]
done

**Comment by luziusmeisser** [comment]
Thanks for the hint. I also fixed this in the upcoming 2024 version of the smart contracts:
https://github.com/Frankencoin-ZCHF/FrankenCoin/commit/e4e051a3549a4d8ef05600fd03d695bc76c48822
